"""Auto-generated by claim2cad.ir_to_cad. Do not edit by hand."""
from __future__ import annotations

import sys
from pathlib import Path

import build123d as bd

HERE = Path(__file__).resolve().parent
REPO_ROOT = HERE.parent.parent
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from claim2cad.ir_schema import ClaimIR
from claim2cad.ir_to_cad import build_compound, export_cad


def gen_step():
    """text-to-cad-compatible envelope (see docs/ARCHITECTURE_NOTES.md §4)."""
    ir = ClaimIR.model_validate_json((HERE / "claim_ir.json").read_text("utf-8"))
    compound, _ = build_compound(ir)
    return {{"shape": compound, "step_output": "model.step"}}


def main() -> None:
    ir = ClaimIR.model_validate_json((HERE / "claim_ir.json").read_text("utf-8"))
    paths = export_cad(ir, HERE)
    for label, path in paths.items():
        print(f"Wrote {{path.name}} ({{path.stat().st_size:,}} B) [{{label}}]")


if __name__ == "__main__":
    main()
